const ingredientDatabase = {
  vegetables: [
    "carrot",
    "broccoli",
    "spinach",
    "tomato",
    "potato",
    "onion",
    "bell pepper",
    "cabbage",
    "cauliflower",
    "celery",
    "zucchini",
    "mushroom",
    "asparagus",
    "green beans",
    "peas",
    "corn",
    "radish",
    "lettuce",
    "kale",
    "swiss chard",
    "brussels sprouts",
    "eggplant",
    "cucumber",
    "beetroot",
    "leek",
    "garlic",
    "ginger",
    "pumpkin",
    "sweet potato",
  ],
  fruits: [
    "apple",
    "banana",
    "orange",
    "strawberry",
    "grape",
    "mango",
    "kiwi",
    "pineapple",
    "watermelon",
    "pear",
    "peach",
    "plum",
    "cherry",
    "blueberry",
    "raspberry",
    "blackberry",
    "lemon",
    "lime",
    "coconut",
    "avocado",
    "pomegranate",
    "fig",
    "date",
    "passion fruit",
    "dragon fruit",
  ],
  proteins: [
    "chicken",
    "beef",
    "fish",
    "tofu",
    "eggs",
    "beans",
    "lentils",
    "shrimp",
    "salmon",
    "tuna",
    "pork",
    "ground beef",
    "turkey",
    "ham",
    "sausage",
    "bacon",
    "lamb",
    "quinoa",
    "chickpeas",
    "tempeh",
    "seitan",
    "duck",
    "veal",
    "venison",
    "crab",
    "lobster",
  ],
  dairy: [
    "milk",
    "cheese",
    "yogurt",
    "butter",
    "sour cream",
    "cream",
    "cottage cheese",
    "whipped cream",
    "ghee",
    "condensed milk",
    "evaporated milk",
    "goat cheese",
    "feta cheese",
    "mozzarella cheese",
    "cheddar cheese",
    "parmesan cheese",
    "blue cheese",
    "cream cheese",
    "ricotta cheese",
    "brie cheese",
    "swiss cheese",
    "provolone cheese",
  ],
  pantry: [
    "rice",
    "pasta",
    "flour",
    "sugar",
    "salt",
    "pepper",
    "olive oil",
    "vegetable oil",
    "coconut oil",
    "soybean oil",
    "canola oil",
    "cornstarch",
    "baking powder",
    "baking soda",
    "yeast",
    "honey",
    "maple syrup",
    "vinegar",
    "soy sauce",
    "worcestershire sauce",
    "ketchup",
    "mayonnaise",
    "mustard",
    "salsa",
    "peanut butter",
    "jam",
    "chocolate chips",
    "cocoa powder",
    "oats",
    "breadcrumbs",
    "nutritional yeast",
    "canned tomatoes",
    "canned beans",
    "canned tuna",
    "canned soup",
    "dried herbs",
    "spaghetti sauce",
    "cornflour",
    "corn flour",
    "corn starch",
    "lemon juice",
  ],
  spices: [
    "cumin",
    "paprika",
    "oregano",
    "cinnamon",
    "chili powder",
    "coriander",
    "turmeric",
    "garlic powder",
    "onion powder",
    "ginger powder",
    "curry powder",
    "nutmeg",
    "cloves",
    "cardamom",
    "allspice",
    "bay leaves",
    "cayenne pepper",
    "dill",
    "rosemary",
    "thyme",
    "basil",
    "parsley",
    "sage",
    "tarragon",
    "mint",
    "fennel seeds",
    "mustard seeds",
    "paprika",
    "smoked paprika",
    "cayenne",
    "red pepper flakes",
  ],
  condiments: [
    "ketchup",
    "mayonnaise",
    "mustard",
    "soy sauce",
    "barbecue sauce",
    "hot sauce",
    "ranch dressing",
    "italian dressing",
    "thousand island dressing",
    "honey mustard",
    "teriyaki sauce",
    "tahini",
    "salsa",
    "guacamole",
    "pesto",
    "hoisin sauce",
    "sriracha",
    "tartar sauce",
    "wasabi",
    "pickle",
    "relish",
    "soybean paste",
    "fish sauce",
    "mirin",
    "oyster sauce",
  ],
  grains: [
    "quinoa",
    "rice",
    "oats",
    "barley",
    "couscous",
    "bulgur",
    "wheat berries",
    "cornmeal",
    "polenta",
    "millet",
    "amaranth",
    "buckwheat",
    "farro",
    "teff",
    "sorghum",
    "spelt",
    "rye",
  ],
  nuts: [
    "almonds",
    "cashews",
    "walnuts",
    "pecans",
    "peanuts",
    "hazelnuts",
    "macadamia nuts",
    "pistachios",
    "pine nuts",
    "sunflower seeds",
    "pumpkin seeds",
    "sesame seeds",
    "flaxseeds",
    "chia seeds",
    "flaked almonds",
  ],
  sweeteners: [
    "sugar",
    "brown sugar",
    "powdered sugar",
    "honey",
    "maple syrup",
    "agave nectar",
    "molasses",
    "corn syrup",
    "stevia",
    "coconut sugar",
    "date syrup",
    "monk fruit sweetener",
    "caster sugar",
    "icing sugar",
  ],
  beverages: [
    "water",
    "coffee",
    "tea",
    "milk",
    "orange juice",
    "apple juice",
    "lemonade",
    "soda",
    "energy drink",
    "smoothie",
    "wine",
    "beer",
    "cocktail",
    "whiskey",
    "vodka",
    "rum",
    "gin",
    "tequila",
  ],
};

export default ingredientDatabase;
